jdbcUrl=jdbc:mysql://localhost:13305/stormify_test
username=stormify
password=Stormify1!
dataSource.cachePrepStmts=true
dataSource.prepStmtCacheSize=250
dataSource.prepStmtCacheSqlLimit=2048
maximumPoolSize=16
