// SPDX-License-Identifier: Apache-2.0
// (C) Panayotis Katsaloulis
package onl.ycode.stormify.biglist

/**
 * A type-safe field path node representing a scalar (leaf) field.
 * Generated by the annotation processor and used with [PagedList.addColumn].
 *
 * Example:
 * ```kotlin
 * list.addColumn(Employee_.name)               // scalar
 * list.addColumn(Employee_.department.name)     // FK chain
 * ```
 */
open class ScalarPath(@JvmField val path: String) {
    fun toPath(): String = path
    override fun toString() = path
}
