// SPDX-License-Identifier: Apache-2.0
// (C) Panayotis Katsaloulis
package onl.ycode.stormify.biglist

import kotlin.jvm.JvmField

/**
 * A type-safe field path node representing a scalar (leaf) field.
 * Generated by the annotation processor and used with [PagedListBase.addColumn].
 *
 * Example:
 * ```kotlin
 * list.addColumn(Employee_.name)               // scalar
 * list.addColumn(Employee_.department.name)     // FK chain
 * ```
 */
open class ScalarPath(
    /** The dot-notation path string, e.g. `"department.name"`. */
    @JvmField val path: String
) {
    /** Returns the dot-notation path string. */
    fun toPath(): String = path

    /** Returns the dot-notation path string. */
    override fun toString() = path
}
