// SPDX-License-Identifier: Apache-2.0
// (C) Panayotis Katsaloulis
package onl.ycode.stormify

/**
 * Controls how a Kotlin property maps to a database column with advanced configuration options.
 *
 * This annotation is **optional**. Most properties work fine without it, using automatic mapping
 * based on naming conventions. Use `@DbField` only when you need:
 * - Custom column names
 * - Primary key configuration
 * - Sequence-based ID generation
 * - Fine-grained control over INSERT/UPDATE operations
 *
 * ## Basic Usage Examples
 *
 * ```kotlin
 * data class User(
 *     // Automatic mapping - no annotation needed
 *     var name: String,        // Maps to column: name
 *     var emailAddress: String // Maps to column: email_address (snake_case)
 * )
 *
 * data class User(
 *     // Custom column name
 *     @DbField(name = "user_id")
 *     var id: Int,
 *
 *     // Primary key with auto-increment
 *     @DbField(primaryKey = true)
 *     var id: Int,
 *
 *     // Primary key with sequence (Oracle/PostgreSQL)
 *     @DbField(primaryKey = true, primarySequence = "user_id_seq")
 *     var id: Int,
 *
 *     // Read-only field (generated by database)
 *     @DbField(creatable = false, updatable = false)
 *     var createdAt: Long,
 *
 *     // Create-only field (set once, never updated)
 *     @DbField(updatable = false)
 *     var createdBy: String,
 *
 *     // Update-only field (skip on insert)
 *     @DbField(creatable = false)
 *     var lastModified: Long
 * )
 * ```
 *
 * ## Primary Key Configuration
 *
 * ```kotlin
 * // Simple auto-increment primary key
 * data class User(
 *     @DbField(primaryKey = true)
 *     var id: Int = 0,
 *     var name: String
 * )
 *
 * // Sequence-based primary key (Oracle/PostgreSQL)
 * data class User(
 *     @DbField(primaryKey = true, primarySequence = "user_id_seq")
 *     var id: Int = 0,
 *     var name: String
 * )
 *
 * // Composite primary key
 * data class OrderDetail(
 *     @DbField(primaryKey = true)
 *     var orderId: Int,
 *     @DbField(primaryKey = true)
 *     var productId: Int,
 *     var quantity: Int
 * )
 * ```
 *
 * ## Field Lifecycle Control
 *
 * ```kotlin
 * data class AuditedEntity(
 *     var id: Int,
 *     var name: String,
 *
 *     // Set by database on INSERT, never updated
 *     @DbField(creatable = false, updatable = false)
 *     var createdAt: Timestamp,
 *
 *     // Set once on INSERT, cannot be changed
 *     @DbField(updatable = false)
 *     var createdBy: String,
 *
 *     // Updated on UPDATE, not set on INSERT
 *     @DbField(creatable = false)
 *     var modifiedAt: Timestamp?,
 *
 *     // Updated on UPDATE, not set on INSERT
 *     @DbField(creatable = false)
 *     var modifiedBy: String?
 * )
 * ```
 *
 * ## Custom Column Mapping
 *
 * ```kotlin
 * data class User(
 *     // Legacy database column name
 *     @DbField(name = "usr_id")
 *     var id: Int,
 *
 *     // Abbreviated column name
 *     @DbField(name = "email")
 *     var emailAddress: String,
 *
 *     // Column with different naming convention
 *     @DbField(name = "FirstName")
 *     var firstName: String
 * )
 * ```
 *
 * ## Comparison with JPA Annotations
 *
 * Stormify also supports JPA annotations:
 *
 * ```kotlin
 * // Stormify annotations
 * @DbField(primaryKey = true)
 * var id: Int
 *
 * // JPA equivalent (also supported)
 * @Id
 * var id: Int
 *
 * // Stormify custom column
 * @DbField(name = "email")
 * var emailAddress: String
 *
 * // JPA equivalent (also supported)
 * @Column(name = "email")
 * var emailAddress: String
 * ```
 *
 * ## Excluding Fields
 *
 * To exclude a field from database operations:
 *
 * ```kotlin
 * data class User(
 *     var id: Int,
 *     var name: String,
 *
 *     // Excluded from all database operations
 *     @Transient
 *     var tempData: String = ""
 * )
 * ```
 *
 * ## Important Notes
 * - Annotation is **optional** - only use when automatic mapping isn't sufficient
 * - Primary key fields should have default values (e.g., `var id: Int = 0`)
 * - `creatable = false, updatable = false` means field is completely managed by database
 * - For composite keys, mark all key fields with `primaryKey = true`
 * - Sequences are database-specific (Oracle, PostgreSQL support, MySQL doesn't)
 *
 * @property name Custom column name. Empty string uses property name with naming policy.
 * @property primaryKey Whether this field is (part of) the primary key.
 * @property primarySequence Sequence name for auto-generating primary key values (Oracle/PostgreSQL).
 * @property creatable Whether field is included in INSERT statements (default: true).
 * @property updatable Whether field is included in UPDATE statements (default: true).
 *
 * @see DbTable
 * @see Stormify.create
 * @see Stormify.update
 */
@Retention(AnnotationRetention.RUNTIME)
annotation class DbField(
    /**
     * The exact name of the column in the database.
     *
     * If not provided (empty string), Stormify uses the property name converted
     * according to the configured naming policy.
     *
     * **Examples:**
     * - `"email"` - maps to column `email`
     * - `"usr_id"` - maps to column `usr_id`
     * - `""` (empty) - uses property name with naming policy
     *
     * @return the database column name, or empty string for automatic naming
     */
    val name: String = "",

    /**
     * Whether this field is a primary key.
     *
     * Set to `true` for primary key fields. For composite keys, mark all key fields
     * with `primaryKey = true`.
     *
     * **Examples:**
     * ```kotlin
     * @DbField(primaryKey = true)
     * var id: Int = 0
     *
     * // Composite key
     * @DbField(primaryKey = true) var orderId: Int
     * @DbField(primaryKey = true) var productId: Int
     * ```
     *
     * @return true if this is a primary key field, false otherwise (default)
     */
    val primaryKey: Boolean = false,

    /**
     * The name of the database sequence used to generate primary key values.
     *
     * Only applicable for databases that support sequences (Oracle, PostgreSQL).
     * Leave empty for auto-increment/IDENTITY columns (MySQL, SQL Server).
     *
     * **Examples:**
     * ```kotlin
     * // PostgreSQL sequence
     * @DbField(primaryKey = true, primarySequence = "user_id_seq")
     * var id: Int = 0
     *
     * // Oracle sequence
     * @DbField(primaryKey = true, primarySequence = "USER_SEQ")
     * var id: Int = 0
     *
     * // MySQL auto-increment (no sequence)
     * @DbField(primaryKey = true)
     * var id: Int = 0
     * ```
     *
     * @return the sequence name, or empty string if not using sequences
     */
    val primarySequence: String = "",

    /**
     * Whether the field value is auto-generated by the database (e.g., AUTO_INCREMENT, SERIAL, IDENTITY).
     *
     * When true, the field is excluded from INSERT statements and its value is read back after insertion.
     * This is equivalent to JPA's `@GeneratedValue(strategy = GenerationType.IDENTITY)`.
     *
     * **Examples:**
     * ```kotlin
     * @DbField(primaryKey = true, autoIncrement = true)
     * var id: Int = 0  // Excluded from INSERT, populated after insert
     * ```
     *
     * @return true if the field value is auto-generated by the database, false otherwise (default)
     */
    val autoIncrement: Boolean = false,

    /**
     * Whether this field is included in INSERT statements.
     *
     * Set to `false` for columns that are:
     * - Generated by database defaults or triggers
     * - Computed columns
     * - Fields that should only be updated, never created
     *
     * **Examples:**
     * ```kotlin
     * // Database-generated timestamp
     * @DbField(creatable = false, updatable = false)
     * var createdAt: Timestamp
     *
     * // Only updated, never set on creation
     * @DbField(creatable = false)
     * var lastModified: Timestamp?
     * ```
     *
     * @return true if included in INSERT (default), false to exclude
     */
    val creatable: Boolean = true,

    /**
     * Whether this field is included in UPDATE statements.
     *
     * Set to `false` for columns that are:
     * - Set once and never changed
     * - Managed entirely by the database
     * - Audit fields that track creation but not modification
     *
     * **Examples:**
     * ```kotlin
     * // Set once on creation
     * @DbField(updatable = false)
     * var createdBy: String
     *
     * // Never modified by application
     * @DbField(creatable = false, updatable = false)
     * var rowVersion: Int
     * ```
     *
     * @return true if included in UPDATE (default), false to exclude
     */
    val updatable: Boolean = true
)
