// SPDX-License-Identifier: Apache-2.0
// (C) Panayotis Katsaloulis
package onl.ycode.stormify

import kotlin.reflect.KClass

/**
 * Functional interface for entity registration callbacks.
 * Typically generated by the annotation processor (annproc) to register [EntityMeta] at startup.
 */
fun interface EntityRegistrar {
    /** Registers entity metadata into the global [EntityMeta] registry. */
    fun register()
}

/**
 * Describes a single property of an entity class, including its type, getter/setter lambdas,
 * and database mapping overrides. Used by [EntityMeta] and the annotation processor.
 *
 * @property name the Kotlin property name
 * @property type the property's Kotlin type
 * @property isReference whether this property is a foreign key reference to another entity
 * @property getter lambda to read the property value from an entity instance
 * @property setter lambda to write a value into the property, with type conversion via [Stormify]
 * @property dbNameOverride explicit database column name, or null to use the [NamingPolicy]
 * @property isPrimaryKey whether this property is part of the primary key
 * @property sequence the database sequence name for auto-generation, or null
 * @property isAutoIncrement whether the database auto-generates this value (IDENTITY columns)
 * @property isCreatable whether this property is included in INSERT statements
 * @property isUpdatable whether this property is included in UPDATE statements
 * @property isTransient whether this property should be excluded from all database operations
 * @property isEnum whether the property type is a Kotlin/Java enum
 * @property enumAsString whether enum values are stored as their string name (`true`) or ordinal/custom integer (`false`)
 */
class PropertyMeta<T : Any>(
    val name: String,
    val type: KClass<*>,
    val isReference: Boolean,
    val getter: (T) -> Any?,
    val setter: (T, Any?, Stormify) -> Unit,
    val dbNameOverride: String?,
    val isPrimaryKey: Boolean,
    val sequence: String?,
    val isAutoIncrement: Boolean = false,
    val isCreatable: Boolean = true,
    val isUpdatable: Boolean = true,
    val isTransient: Boolean = false,
    val isEnum: Boolean = false,
    val enumAsString: Boolean = false,
)

/**
 * Compile-time metadata for a mapped entity class. Holds the class reference, a constructor lambda,
 * property descriptors, and an optional table name override.
 *
 * On Native platforms, instances are generated by the annotation processor (annproc) and registered
 * via [EntityRegistrar]. On JVM, metadata can also be created at runtime via reflection.
 *
 * @property type the Kotlin class this metadata describes
 * @property constructor lambda that creates a new instance of the entity
 * @property properties the list of mapped property descriptors
 * @property tableNameOverride explicit table name, or null to derive from the class name via [NamingPolicy]
 */
class EntityMeta<T : Any>(
    val type: KClass<T>,
    val constructor: () -> T,
    val properties: List<PropertyMeta<T>>,
    val tableNameOverride: String?,
) {
    /** Global registry of compile-time entity metadata, populated by [EntityRegistrar] callbacks. */
    companion object {
        private val registry = mutableMapOf<KClass<*>, EntityMeta<*>>()

        /** Registers entity metadata so it can be looked up later by [find]. */
        fun register(meta: EntityMeta<*>) {
            registry[meta.type] = meta
        }

        /** Looks up previously registered metadata for the given [type], or returns null. */
        @Suppress("UNCHECKED_CAST")
        fun <T : Any> find(type: KClass<T>): EntityMeta<T>? =
            registry[type] as? EntityMeta<T>

        /** Classloader-leak cleanup hook — on JVM, invoked by `StormifyLifecycle.clear()`. */
        internal fun clearRegistry() = registry.clear()
    }
}

/**
 * Registry for enum classes, used by native targets where reflection is not available.
 * On JVM, enum operations use reflection directly and this registry is not needed.
 * On native, the annotation processor generates calls to [register] at startup.
 */
object EnumRegistry {
    private data class EnumFunctions(
        val entries: Array<out Enum<*>>,
        val isDbValue: Boolean,
        val toInt: (Any) -> Int
    )

    private val registry = mutableMapOf<KClass<*>, EnumFunctions>()

    /**
     * Registers the enum constants and int encoder for the given enum class. Called
     * by annproc-generated code at startup; user code normally does not invoke this
     * directly. [fromInt] and [fromName] are derived from [entries] on each lookup.
     */
    fun register(
        enumClass: KClass<*>,
        entries: Array<out Enum<*>>,
        toInt: (Any) -> Int
    ) {
        registry[enumClass] = EnumFunctions(entries, entries.firstOrNull() is DbValue, toInt)
    }

    /** Returns `true` if [enumClass] has been registered via [register]. */
    fun isRegistered(enumClass: KClass<*>): Boolean = registry.containsKey(enumClass)

    /** Returns the registered enum constants for [enumClass], or `null` if not registered. */
    fun entriesOf(enumClass: KClass<*>): Array<out Enum<*>>? =
        registry[enumClass]?.entries

    /**
     * Returns the enum constant of [enumClass] whose integer value (ordinal or
     * [DbValue.dbValue]) is [value], or `null` if [enumClass] is not registered or no
     * matching constant exists.
     */
    @Suppress("UNCHECKED_CAST")
    fun <T : Any> fromInt(enumClass: KClass<T>, value: Int): T? {
        val fns = registry[enumClass] ?: return null
        val match = if (fns.isDbValue)
            fns.entries.firstOrNull { (it as DbValue).dbValue == value }
        else
            fns.entries.getOrNull(value)
        return match as T?
    }

    /**
     * Returns the enum constant of [enumClass] whose name is [name] (case-insensitive),
     * or `null` if [enumClass] is not registered or no matching constant exists.
     */
    @Suppress("UNCHECKED_CAST")
    fun <T : Any> fromName(enumClass: KClass<T>, name: String): T? {
        val entries = registry[enumClass]?.entries ?: return null
        return entries.firstOrNull { it.name.equals(name, ignoreCase = true) } as T?
    }

    /**
     * Returns the integer value (ordinal or [DbValue.dbValue]) for the given enum
     * constant, or `null` if the constant's class has not been registered.
     */
    fun toInt(value: Any): Int? =
        registry[value::class]?.toInt?.invoke(value)

    /** Classloader-leak cleanup hook — on JVM, invoked by `StormifyLifecycle.clear()`. */
    internal fun clearRegistry() = registry.clear()
}
