package onl.ycode.stormify;

import static onl.ycode.stormify.StormifyManager.stormify;

/**
 * Dialect-aware DDL helper for cross-database testing.
 * Provides SQL fragments that work correctly for each supported database.
 */
public class TestDDL {

    private static SqlDialect dialect() {
        return stormify().getSqlDialect();
    }

    private static boolean isOracle() {
        SqlDialect d = dialect();
        return d == SqlDialect.ORACLE_NEW || d == SqlDialect.ORACLE_OLD;
    }

    private static boolean isMssql() {
        SqlDialect d = dialect();
        return d == SqlDialect.SQL_SERVER_NEW || d == SqlDialect.SQL_SERVER_OLD;
    }

    private static boolean isSqlite() {
        return dialect() == SqlDialect.SQLITE;
    }

    /**
     * Returns the appropriate text column type for the current dialect.
     */
    static String textType() {
        if (isOracle()) return "VARCHAR2(4000)";
        if (isMssql()) return "NVARCHAR(MAX)";
        return "TEXT";
    }

    /**
     * Returns the appropriate timestamp column type for the current dialect.
     * Note: MSSQL's TIMESTAMP is a binary row-version, not a datetime.
     */
    static String timestampType() {
        if (isMssql()) return "DATETIME2";
        return "TIMESTAMP";
    }

    /**
     * Returns the integer primary key column definition.
     */
    static String intPrimaryKey(String colName) {
        if (isOracle()) return colName + " NUMBER(10) PRIMARY KEY";
        return colName + " INT PRIMARY KEY";
    }

    /**
     * Returns an auto-increment primary key column definition, or null if the dialect
     * does not support it. Tests should skip when this returns null.
     */
    static String autoIncrementPrimaryKey(String colName) {
        SqlDialect d = dialect();
        switch (d) {
            case MYSQL_OLD:
            case MYSQL_NEW:
            case MARIA_DB_OLD:
            case MARIA_DB_NEW:
                return colName + " INT PRIMARY KEY AUTO_INCREMENT";
            case POSTGRESQL:
                return colName + " SERIAL PRIMARY KEY";
            case ORACLE_NEW:
                return colName + " NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            case SQL_SERVER_NEW:
            case SQL_SERVER_OLD:
                return colName + " INT IDENTITY(1,1) PRIMARY KEY";
            case SQLITE:
                return colName + " INTEGER PRIMARY KEY AUTOINCREMENT";
            default:
                return null;
        }
    }

    /**
     * Returns a NOT NULL integer column definition.
     */
    static String intNotNull(String colName) {
        if (isOracle()) return colName + " NUMBER(10) NOT NULL";
        return colName + " INT NOT NULL";
    }

    /**
     * Returns an integer column definition (nullable).
     */
    static String intColumn(String colName) {
        if (isOracle()) return colName + " NUMBER(10)";
        return colName + " INT";
    }

    /**
     * Wraps a simple expression in a SELECT that works on all dialects.
     * Oracle requires FROM dual for expression-only SELECTs.
     */
    static String selectExpr(String expr) {
        if (isOracle()) return "SELECT " + expr + " FROM dual";
        return "SELECT " + expr;
    }

    /**
     * Returns true if the current dialect supports auto-increment columns.
     */
    static boolean supportsAutoIncrement() {
        return autoIncrementPrimaryKey("x") != null;
    }

    /**
     * Returns true if the current dialect supports high-concurrency stress testing.
     */
    static boolean supportsHighConcurrency() {
        return !isSqlite();
    }

    /**
     * Drops a table if it exists. Handles Oracle's lack of DROP TABLE IF EXISTS.
     * This is for test cleanup, not testing Stormify's DROP support.
     */
    static void dropTable(String tableName) {
        if (isOracle()) {
            try {
                stormify().executeUpdate("DROP TABLE " + tableName);
            } catch (QueryException e) {
                // ORA-00942: table or view does not exist — that's fine, anything else rethrow
                Throwable cause = e;
                while (cause != null) {
                    if (cause instanceof java.sql.SQLException && ((java.sql.SQLException) cause).getErrorCode() == 942)
                        return;
                    cause = cause.getCause();
                }
                throw e;
            }
        } else {
            stormify().executeUpdate("DROP TABLE IF EXISTS " + tableName);
        }
    }

    /**
     * Returns a CREATE TABLE statement.
     * Call dropTable() manually before this, respecting FK dependency order.
     */
    static String createTable(String tableName, String columns) {
        return "CREATE TABLE " + tableName + " (" + columns + ")";
    }

    /**
     * Returns a foreign key clause.
     */
    static String foreignKey(String column, String refTable, String refColumn) {
        return "FOREIGN KEY(" + column + ") REFERENCES " + refTable + "(" + refColumn + ")";
    }
}
