package onl.ycode.stormify.schemasync.model

import kotlinx.serialization.Serializable

/**
 * DDL templates for deterministic Kotlin types (those that do not require slot classification).
 * Each entry is the SQL fragment used when the migration generator emits a column of that
 * Kotlin type. Override per-project via the F6 Defaults window in the TUI.
 *
 * Primary-key entries (`pkInt`, `pkLong`, `pkAutoInt`, `pkAutoLong`) cover the PK column
 * exclusively; references (`var owner: User`) get the target's PK type via FK resolution
 * but are emitted without auto-increment syntax.
 */
@Serializable
data class DefaultsProfile(
    val booleanDdl: String = "BOOLEAN",
    val localDateDdl: String = "DATE",
    val localTimeDdl: String = "TIME",
    val offsetTimeDdl: String = "TIME WITH TIME ZONE",
    val localDateTimeDdl: String = "TIMESTAMP",
    val instantDdl: String = "TIMESTAMP WITH TIME ZONE",
    val byteArrayDdl: String = "BLOB",
    val charArrayDdl: String = "CLOB",
    val uuidDdl: String = "UUID",
    val enumOrdinalDdl: String = "SMALLINT",

    val pkIntDdl: String = "INT",
    val pkLongDdl: String = "BIGINT",
    val pkAutoIntDdl: String = "INT GENERATED BY DEFAULT AS IDENTITY",
    val pkAutoLongDdl: String = "BIGINT GENERATED BY DEFAULT AS IDENTITY",

    /**
     * Auto-defaults emitted as SQL `DEFAULT <value>` when a NOT NULL field has
     * no explicit literal initializer in the entity. Empty string disables
     * auto-default for that type (the migration falls back to a TODO comment).
     */
    val autoDefaultText: String = "''",
    val autoDefaultInt: String = "0",
    val autoDefaultDecimal: String = "0",
    val autoDefaultBoolean: String = "FALSE",
    val autoDefaultLocalDate: String = "",
    val autoDefaultLocalTime: String = "",
    val autoDefaultLocalDateTime: String = "",
    val autoDefaultInstant: String = "",
    val autoDefaultUuid: String = "",
    val autoDefaultBytes: String = "",

    val postgresql: DialectOverride = DialectOverride(),
    val mysql: DialectOverride = DialectOverride(),
    val mariadb: DialectOverride = DialectOverride(),
    val oracle: DialectOverride = DialectOverride(),
    val mssql: DialectOverride = DialectOverride(),
    val sqlite: DialectOverride = DialectOverride(),
) {
    /** Returns this profile with the given dialect's overrides applied (nulls in override fall back). */
    fun mergedFor(dialectKey: String): DefaultsProfile {
        val o = when (dialectKey) {
            "postgresql" -> postgresql
            "mysql" -> mysql
            "mariadb" -> mariadb
            "oracle" -> oracle
            "mssql" -> mssql
            "sqlite" -> sqlite
            else -> return this
        }
        return copy(
            booleanDdl = o.booleanDdl ?: booleanDdl,
            localDateDdl = o.localDateDdl ?: localDateDdl,
            localTimeDdl = o.localTimeDdl ?: localTimeDdl,
            localDateTimeDdl = o.localDateTimeDdl ?: localDateTimeDdl,
            instantDdl = o.instantDdl ?: instantDdl,
            byteArrayDdl = o.byteArrayDdl ?: byteArrayDdl,
            charArrayDdl = o.charArrayDdl ?: charArrayDdl,
            uuidDdl = o.uuidDdl ?: uuidDdl,
            enumOrdinalDdl = o.enumOrdinalDdl ?: enumOrdinalDdl,
            pkIntDdl = o.pkIntDdl ?: pkIntDdl,
            pkLongDdl = o.pkLongDdl ?: pkLongDdl,
            pkAutoIntDdl = o.pkAutoIntDdl ?: pkAutoIntDdl,
            pkAutoLongDdl = o.pkAutoLongDdl ?: pkAutoLongDdl,
            autoDefaultText = o.autoDefaultText ?: autoDefaultText,
            autoDefaultInt = o.autoDefaultInt ?: autoDefaultInt,
            autoDefaultDecimal = o.autoDefaultDecimal ?: autoDefaultDecimal,
            autoDefaultBoolean = o.autoDefaultBoolean ?: autoDefaultBoolean,
            autoDefaultLocalDate = o.autoDefaultLocalDate ?: autoDefaultLocalDate,
            autoDefaultLocalTime = o.autoDefaultLocalTime ?: autoDefaultLocalTime,
            autoDefaultLocalDateTime = o.autoDefaultLocalDateTime ?: autoDefaultLocalDateTime,
            autoDefaultInstant = o.autoDefaultInstant ?: autoDefaultInstant,
            autoDefaultUuid = o.autoDefaultUuid ?: autoDefaultUuid,
            autoDefaultBytes = o.autoDefaultBytes ?: autoDefaultBytes,
        )
    }
}

/** Per-dialect override; any null falls back to the base [DefaultsProfile]. */
@Serializable
data class DialectOverride(
    val booleanDdl: String? = null,
    val localDateDdl: String? = null,
    val localTimeDdl: String? = null,
    val localDateTimeDdl: String? = null,
    val instantDdl: String? = null,
    val byteArrayDdl: String? = null,
    val charArrayDdl: String? = null,
    val uuidDdl: String? = null,
    val enumOrdinalDdl: String? = null,
    val pkIntDdl: String? = null,
    val pkLongDdl: String? = null,
    val pkAutoIntDdl: String? = null,
    val pkAutoLongDdl: String? = null,
    val autoDefaultText: String? = null,
    val autoDefaultInt: String? = null,
    val autoDefaultDecimal: String? = null,
    val autoDefaultBoolean: String? = null,
    val autoDefaultLocalDate: String? = null,
    val autoDefaultLocalTime: String? = null,
    val autoDefaultLocalDateTime: String? = null,
    val autoDefaultInstant: String? = null,
    val autoDefaultUuid: String? = null,
    val autoDefaultBytes: String? = null,
)
