// SPDX-License-Identifier: Apache-2.0
// (C) Panayotis Katsaloulis
package test

import onl.ycode.stormify.SqlDialect
import onl.ycode.stormify.Stormify

object TestDDL {
    private lateinit var stormify: Stormify

    fun init(s: Stormify) { stormify = s }

    private val dialect get() = stormify.sqlDialect
    private val isOracle get() = dialect == SqlDialect.ORACLE_NEW || dialect == SqlDialect.ORACLE_OLD
    private val isMssql get() = dialect == SqlDialect.SQL_SERVER_NEW || dialect == SqlDialect.SQL_SERVER_OLD
    private val isSqlite get() = dialect == SqlDialect.SQLITE

    fun textType() = when {
        isOracle -> "VARCHAR2(4000)"
        isMssql -> "NVARCHAR(MAX)"
        else -> "TEXT"
    }

    fun timestampType() = if (isMssql) "DATETIME2" else "TIMESTAMP"

    fun intPrimaryKey(col: String) = if (isOracle) "$col NUMBER(10) PRIMARY KEY" else "$col INT PRIMARY KEY"

    fun intNotNull(col: String) = if (isOracle) "$col NUMBER(10) NOT NULL" else "$col INT NOT NULL"

    fun intColumn(col: String) = if (isOracle) "$col NUMBER(10)" else "$col INT"

    fun autoIncrementPrimaryKey(col: String): String? = when (dialect) {
        SqlDialect.MYSQL_OLD, SqlDialect.MYSQL_NEW,
        SqlDialect.MARIA_DB_OLD, SqlDialect.MARIA_DB_NEW -> "$col INT PRIMARY KEY AUTO_INCREMENT"
        SqlDialect.POSTGRESQL -> "$col SERIAL PRIMARY KEY"
        SqlDialect.ORACLE_NEW -> "$col NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        SqlDialect.SQL_SERVER_NEW, SqlDialect.SQL_SERVER_OLD -> "$col INT IDENTITY(1,1) PRIMARY KEY"
        SqlDialect.SQLITE -> "$col INTEGER PRIMARY KEY AUTOINCREMENT"
        else -> null
    }

    fun supportsAutoIncrement() = autoIncrementPrimaryKey("x") != null
    fun supportsHighConcurrency() = !isSqlite

    fun foreignKey(column: String, refTable: String, refColumn: String) =
        "FOREIGN KEY($column) REFERENCES $refTable($refColumn)"

    fun createTable(name: String, columns: String) = "CREATE TABLE $name ($columns)"

    fun selectExpr(expr: String) = if (isOracle) "SELECT $expr FROM dual" else "SELECT $expr"

    fun dropTable(name: String) {
        if (isOracle) {
            try {
                stormify.executeUpdate("DROP TABLE $name")
            } catch (_: Exception) {
                // ORA-00942: table or view does not exist — safe to ignore on Oracle
            }
        } else {
            stormify.executeUpdate("DROP TABLE IF EXISTS $name")
        }
    }
}
