package onl.ycode.kdbc.oracle

import kotlinx.cinterop.*
import odpi.*
import cnames.structs.*

/**
 * Type aliases for ODPI-C opaque types.
 * ODPI-C uses opaque handles that cinterop exposes as forward-declared structs from odpi package.
 */
// These types are generated by cinterop from dpi.h
// They're available in the `odpi` package as: dpiContext, dpiConn, etc.

// ODPI-C Result Constants
const val DPI_SUCCESS = 0
const val DPI_FAILURE = -1

// ODPI-C Mode Constants
const val DPI_MODE_CONN_CLOSE_DEFAULT = 0x0000u
const val DPI_MODE_CONN_CLOSE_DROP = 0x0001u
const val DPI_MODE_CONN_CLOSE_RETAG = 0x0002u

// ODPI-C Execution Modes
const val DPI_MODE_EXEC_DEFAULT = 0x00000000u
const val DPI_MODE_EXEC_DESCRIBE_ONLY = 0x00000010u
const val DPI_MODE_EXEC_COMMIT_ON_SUCCESS = 0x00000020u
const val DPI_MODE_EXEC_BATCH_ERRORS = 0x00000080u
const val DPI_MODE_EXEC_PARSE_ONLY = 0x00000100u
const val DPI_MODE_EXEC_ARRAY_DML_ROWCOUNTS = 0x00100000u

// ODPI-C Fetch Mode Constants
const val DPI_MODE_FETCH_NEXT = 0x00000002u
const val DPI_MODE_FETCH_FIRST = 0x00000004u
const val DPI_MODE_FETCH_LAST = 0x00000008u
const val DPI_MODE_FETCH_PRIOR = 0x00000010u
const val DPI_MODE_FETCH_ABSOLUTE = 0x00000020u
const val DPI_MODE_FETCH_RELATIVE = 0x00000040u

// ODPI-C Oracle Type Constants (dpiOracleTypeNum)
// These map to Oracle internal type numbers
const val DPI_ORACLE_TYPE_NONE = 0u
const val DPI_ORACLE_TYPE_VARCHAR = 1u
const val DPI_ORACLE_TYPE_NUMBER = 2u
const val DPI_ORACLE_TYPE_LONG = 8u
const val DPI_ORACLE_TYPE_DATE = 12u
const val DPI_ORACLE_TYPE_RAW = 23u
const val DPI_ORACLE_TYPE_LONG_RAW = 24u
const val DPI_ORACLE_TYPE_CHAR = 96u
const val DPI_ORACLE_TYPE_BINARY_FLOAT = 100u
const val DPI_ORACLE_TYPE_BINARY_DOUBLE = 101u
const val DPI_ORACLE_TYPE_ROWID = 104u
const val DPI_ORACLE_TYPE_CLOB = 112u
const val DPI_ORACLE_TYPE_BLOB = 113u
const val DPI_ORACLE_TYPE_BFILE = 114u
const val DPI_ORACLE_TYPE_TIMESTAMP = 180u
const val DPI_ORACLE_TYPE_TIMESTAMP_TZ = 181u
const val DPI_ORACLE_TYPE_TIMESTAMP_LTZ = 231u
const val DPI_ORACLE_TYPE_BOOLEAN = 252u

// ODPI-C Native Type Constants (dpiNativeTypeNum)
// These determine how ODPI-C presents data to the application
const val DPI_NATIVE_TYPE_INT64 = 3000u
const val DPI_NATIVE_TYPE_UINT64 = 3001u
const val DPI_NATIVE_TYPE_FLOAT = 3002u
const val DPI_NATIVE_TYPE_DOUBLE = 3003u
const val DPI_NATIVE_TYPE_BYTES = 3004u
const val DPI_NATIVE_TYPE_TIMESTAMP = 3005u
const val DPI_NATIVE_TYPE_INTERVAL_DS = 3006u
const val DPI_NATIVE_TYPE_INTERVAL_YM = 3007u
const val DPI_NATIVE_TYPE_LOB = 3008u
const val DPI_NATIVE_TYPE_OBJECT = 3009u
const val DPI_NATIVE_TYPE_STMT = 3010u
const val DPI_NATIVE_TYPE_BOOLEAN = 3011u
const val DPI_NATIVE_TYPE_ROWID = 3012u

// Statement Types
const val DPI_STMT_TYPE_UNKNOWN = 0u
const val DPI_STMT_TYPE_SELECT = 1u
const val DPI_STMT_TYPE_UPDATE = 2u
const val DPI_STMT_TYPE_DELETE = 3u
const val DPI_STMT_TYPE_INSERT = 4u
const val DPI_STMT_TYPE_CREATE = 5u
const val DPI_STMT_TYPE_DROP = 6u
const val DPI_STMT_TYPE_ALTER = 7u
const val DPI_STMT_TYPE_BEGIN = 8u
const val DPI_STMT_TYPE_DECLARE = 9u
const val DPI_STMT_TYPE_CALL = 10u

// Version numbers (to be used with dpiContext_createWithParams)
const val DPI_MAJOR_VERSION = 5u
const val DPI_MINOR_VERSION = 6u
